### ISSUE TITLE
Error: Cannot find module 'commander'

### ISSUE THREAD

**Issue by z977780633** [hktalent/myhktools#1]
onlydeMac:myhktools only$ npm install -g commander
⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ rollbackFailedOptional: verb npm-session 6a03942a6593851
+ commander@2.11.0
updated 1 package in 32.375s
onlydeMac:myhktools only$ 
onlydeMac:myhktools only$ node checkUrl.js -i
module.js:491
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/github/myhktools/checkUrl.js:2:16)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
onlydeMac:myhktools only$ ls -ld /usr/local/lib/node_modules/* | awk '{print $9}'|sed -e 's/\/usr\/local\/lib\/node_modules\///g'
commander
npm

**Comment by hktalent** [comment]
1、
git pull

2、
npm install
